import type { NextPage } from 'next';
import Head from 'next/head';
import { Box, Center, Text } from '@mantine/core';
import Wrapper from '../components/Wrapper';
import Image from 'next/image';

const Credits: NextPage = () => {
  return (
    <>
      <Wrapper>
        <Box
          component="main"
          sx={{
            padding: '2rem',
          }}
        >
          <Head>
            <title>credits</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/main-favicon/favicon.ico" />
            <link
              rel="apple-touch-icon"
              sizes="180x180"
              href="/main-favicon/apple-touch-icon.png"
            />
            <link
              rel="icon"
              type="image/png"
              sizes="32x32"
              href="/main-favicon/favicon-32x32.png"
            />
            <link
              rel="icon"
              type="image/png"
              sizes="16x16"
              href="/main-favicon/favicon-16x16.png"
            />
            <link rel="manifest" href="/main-favicon/site.webmanifest" />
          </Head>
          <Box>
            <Center>
              <Text
                sx={{
                  fontSize: '3rem',
                  fontFamily: 'Crete Round',
                }}
              >
                credits
              </Text>
            </Center>
            <Box>
              <a
                href="https://www.flaticon.com/free-icons/development"
                title="development icons"
              >
                Development icons created by Freepik - Flaticon
              </a>
            </Box>
          </Box>
        </Box>
      </Wrapper>
    </>
  );
};

export default Credits;
